export const Styles = {
    FontFamily: {
        sFProText: "SF Pro Text",
        sFProDisplay: "SF Pro Display",
        robotoRegular: "Roboto-Regular",
        robotoBold: "Roboto-Bold",
    },
    FontSize: {
        sm: 14,
        mid: 17,
        xl11: 30,
        base: 16,
        xl3: 22,
        lg: 18,
        mini: 15,
        xl15: 34,
        xs: 12,
    },
    Color: {
        background: "#f6f5f5",
        white: "#fff",
        textSecondary: "#9586a8",
        selectedBGViolet: "#e2cbff",
        colorBlueviolet_100: "#6c0ee4",
        border: "#d9d0e3",
        textPrimary: "#2d0c57",
        primaryButton: "#0bce83",
        selectedViolet: "#7203ff",
    },
    Padding: {
        mini: 15,
        xs9: 4,
        xl10: 29,
        xs3: 10,
        base: 16,
    },
    Border: {
        xl5: 24,
        xl8: 27,
        xs5: 8,
        xs6_2: 6,
        xl11: 30,
        mid: 17,
    },
};